db:
  # postgresql://[user[:password]@][netloc][:port][,...][/dbname][?param1=value1&...]
  url: ''

sessionSecret: qwerty

# https://console.cloud.google.com/apis/credentials
socialLogin:
  google:
    clientID: ''
    clientSecret: ''
    callbackURL: ''
