db:
  # postgresql://[user[:password]@][netloc][:port][,...][/dbname][?param1=value1&...]
  url: postgresql://postgres:qwerty@127.0.0.1:5433/postgres

sessionSecret: qwerty

# https://console.cloud.google.com/apis/credentials
socialLogin:
  google:
    clientID: ''
    clientSecret: ''
    callbackURL: ''
